"""add nutrition snapshot fields

Revision ID: 2daef35e71aa
Revises: dbd8bbc0ddb3
Create Date: 2026-08-14 22:55:39.557209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2daef35e71aa'
down_revision: Union[str, Sequence[str], None] = 'dbd8bbc0ddb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_logs', sa.Column('calories', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('protein_g', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('carbs_g', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('fat_g', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('fiber_g', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('nutrition_logs', sa.Column('source_food_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrition_logs', 'source_food_id')
    op.drop_column('nutrition_logs', 'source')
    op.drop_column('nutrition_logs', 'fiber_g')
    op.drop_column('nutrition_logs', 'fat_g')
    op.drop_column('nutrition_logs', 'carbs_g')
    op.drop_column('nutrition_logs', 'protein_g')
    op.drop_column('nutrition_logs', 'calories')
    # ### end Alembic commands ###
